<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27" started-at="2017-08-04T06:21:18Z" finished-at="2017-08-04T06:21:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27" started-at="2017-08-04T06:21:18Z" finished-at="2017-08-04T06:21:18Z">
      <class name="com.loylty.mobileautomation.testcases.SBI_Test">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.loylty.mobileautomation.testcases.SBI_Test@617faa95]" name="setUp" is-config="true" duration-ms="283" started-at="2017-08-04T11:51:18Z" finished-at="2017-08-04T11:51:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verify_humberger_SBI(java.lang.String, java.lang.String)[pri:0, instance:com.loylty.mobileautomation.testcases.SBI_Test@617faa95]" name="verify_humberger_SBI" duration-ms="5" started-at="2017-08-04T11:51:18Z" data-provider="defaultDP" finished-at="2017-08-04T11:51:18Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 0 parameters but the method com.loylty.mobileautomation.testcases.SBI_Test#verify_humberger_SBI takes 2 and TestNG is unable in inject a suitable object]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method com.loylty.mobileautomation.testcases.SBI_Test#verify_humberger_SBI takes 2 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1253)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1122)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1249)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_humberger_SBI -->
        <test-method status="PASS" signature="email_report()[pri:0, instance:com.loylty.mobileautomation.testcases.SBI_Test@617faa95]" name="email_report" is-config="true" duration-ms="0" started-at="2017-08-04T11:51:18Z" finished-at="2017-08-04T11:51:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email_report -->
      </class> <!-- com.loylty.mobileautomation.testcases.SBI_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
